### ISSUE TITLE
Adding Technical Support Committee names to the website?

### ISSUE THREAD

**Issue by iut62elec** [arras-energy/static-website#12]
Can we add Technical Support Committee names to the website?

**Comment by dchassin** [comment]
See https://github.com/arras-energy/tsc/blob/main/meetings/2023-09-21.md for a list of members.

**Comment by melodyxnguyen** [comment]
Hi @iut62elec! Yes we definitely can add the TSC names onto the website. The committee names will be listed under the "Partnerships" page which can be found by navigating through the menu bar. Hope this helps!
